### ISSUE TITLE
Build on Linux - Errors

### ISSUE THREAD

**Issue by AIAdventures** [zhouyan/MCKL#1]
Hi Awesome library.
HAving problems with the build though

andrewcz@andrewcz-PORTEGE-Z30t-B ~/MCKL/build $ cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test SSE2_TEST
-- Performing Test SSE2_TEST - Failed
-- Performing Test AVX2_TEST
-- Performing Test AVX2_TEST - Failed
-- Performing Test AESNI_TEST
-- Performing Test AESNI_TEST - Failed
-- Performing Test RDRAND_TEST
-- Performing Test RDRAND_TEST - Failed
-- Performing Test BMI2_TEST
-- Performing Test BMI2_TEST - Failed
-- Performing Test FMA_TEST
-- Performing Test FMA_TEST - Failed
-- The ASM_NASM compiler identification is unknown
-- Didn't find assembler
CMake Error at cmake/MCKL.cmake:198 (enable_language):
  No CMAKE_ASM_NASM_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM_NASM" or the CMake cache entry CMAKE_ASM_NASM_COMPILER to the
  full path to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:72 (include)

-- Configuring incomplete, errors occurred!
See also "/home/andrewcz/MCKL/build/CMakeFiles/CMakeOutput.log".
See also "/home/andrewcz/MCKL/build/CMakeFiles/CMakeError.log"

Please assist.
MAny thanks,
Andrew

**Comment by zhouyan** [comment]
The error message is pretty clear, you need to tell cmake where to find NASM assembler. In addition, you need to use C++14 mode (C++11 probably will still work)

Best,

Yan Zhou

**Comment by AIAdventures** [comment]
ong unsigned int; std::string = std::basic_string<char>]’
/home/andrewcz/MCKL/example/random/src/random_test.cpp:127:61:   required from here
/usr/include/c++/4.8/bits/stl_vector.h:168:25: error: ‘struct std::_Vector_base<long unsigned int, mckl::Allocator<long unsigned int> >::_Vector_impl’ has no member named ‘allocate’
       { return __n != 0 ? _M_impl.allocate(__n) : 0; }
                         ^
make[3]: *** [example/random/CMakeFiles/librandom_test.dir/src/random_test.cpp.o] Error 1
make[2]: *** [example/random/CMakeFiles/librandom_test.dir/all] Error 2
make[1]: *** [CMakeFiles/example.dir/rule] Error 2
make: *** [example] Error 2
andrewcz@andrewcz-PORTEGE-Z30t-B ~/MCKL/build $ 

This is when i try and build the example

**Comment by zhouyan** [comment]
As I said, you need C++14 compiler.

Best,

Yan Zhou

**Comment by AIAdventures** [comment]
ah ok

**Comment by AIAdventures** [comment]
thank you :)

**Comment by AIAdventures** [comment]
still was not able to build the examples

**Comment by AIAdventures** [comment]
is there an easy c++14 to download?

**Comment by AIAdventures** [comment]
, mckl::Allocator<double> >}’ and ‘mckl::Matrix<double, (mckl::MatrixLayout)102, mckl::Allocator<double> >::size_type {aka long unsigned int}’)
make[3]: *** [example/utility/CMakeFiles/utility_hdf5.dir/src/utility_hdf5.cpp.o] Error 1
make[2]: *** [example/utility/CMakeFiles/utility_hdf5.dir/all] Error 2
make[1]: *** [CMakeFiles/example.dir/rule] Error 2
make: *** [example] Error 2
andrewcz@andrewcz-PORTEGE-Z30t-B ~/MCKL/build $

**Comment by zhouyan** [comment]
You can use GCC 6, Clang 3.8 or late.. As to how to get a newer compiler, you need to ask elsewhere. For GCC4.8, maybe you first try C++11. I am not sure if it still work, but MCKL used to use only C++11.

Best,

Yan Zhou

**Comment by zhouyan** [comment]
Well, it won't work. You need C++14

**Comment by AIAdventures** [comment]
andrewcz@andrewcz-PORTEGE-Z30t-B ~ $ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.5 (Ubuntu 4.8.5-2ubuntu1~14.04.1)

**Comment by AIAdventures** [comment]
I think i have c++ 14 installed

**Comment by AIAdventures** [comment]
andrewcz@andrewcz-PORTEGE-Z30t-B ~ $ sudo apt-get install g++-4.9
[sudo] password for andrewcz: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++-4.9 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
andrewcz@andrewcz-PORTEGE-Z30t-B ~ $

**Comment by zhouyan** [comment]
You need to turn on the C++14 flag. Pass `std=c++14` to CMake's CXXFLAGS, in addition, to get reasonable performance on newer CPU, you need to pass relevant arch flags, e.g, `-march=native`

**Comment by zhouyan** [comment]
Try `CXX=g++-4.9 CXXFLAGS="-std=c++14" cmake ..`. Replace `g++-4.9` with the name/path to your C++14 compiler
